---
global:
  measurements:
    - name: volumeSnapshotLatency

metricsEndpoints:
  - indexer:
      type: local
      metricsDirectory: collected-metrics

jobs:
  - name: vmsnapshot-provision
    jobType: create
    jobIterations: 1
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespace: {{.NAMESPACE}}
    namespacedIterations: false
    waitWhenFinished: true
    maxWaitTimeout: {{.MAX_WAIT}}
    objects:
      - objectTemplate: templates/vm.yaml
        replicas: {{.REPLICAS}}
        inputVars:
          storageClass: {{.STORAGE_CLASS}}
          vmImage: {{.VM_IMAGE}}
          diskSize: {{.DISK_SIZE}}

# SNAPSHOT_JOBS
